version: '3'

services:
  v2ray:
    image: v2fly/v2fly-core
    container_name: v2ray
    ports:
      - "${V2RAY_PORT}:80"
    environment:
      V2RAY_PORT: ${V2RAY_PORT}
      V2RAY_PATH: ${V2RAY_PATH}
      V2RAY_HOST: ${V2RAY_HOST}
      V2RAY_ID: ${V2RAY_ID}
    volumes:
      - ./config.json:/etc/v2ray/config.json
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["/entrypoint.sh"]
    command: ["v2ray", "-config", "/etc/v2ray/config.json"]
